ReadingJournalApp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

base/urls.py
from django.urls import path
from .views import TaskList, TaskDetail, TaskCreate, TaskUpdate, DeleteView, CustomLoginView, RegisterPage, TaskReorder
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_views
from . import views
urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('register/', RegisterPage.as_view(), name='register'),

    path('', TaskList.as_view(), name='tasks'),
    path('task/<int:pk>/', TaskDetail.as_view(), name='task'),
    path('task-create/', TaskCreate.as_view(), name='task-create'),
    path('task-update/<int:pk>/', TaskUpdate.as_view(), name='task-update'),
    path('task-delete/<int:pk>/', DeleteView.as_view(), name='task-delete'),
    path('task-reorder/', TaskReorder.as_view(), name='task-reorder'),
    # path('save-thought', views.save_thought, name='save-thought'),

    path('reset_password/',
         auth_views.PasswordResetView.as_view(template_name="base/password_reset.html"),
         name="reset_password"),

    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(template_name="base/password_reset_sent.html"),
         name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="base/password_reset_form.html"),
         name="password_reset_confirm"),

    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name="base/password_reset_done.html"),
         name="password_reset_complete"),

]
'''
1 - Submit email form                         //PasswordResetView.as_view()
2 - Email sent success message                //PasswordResetDoneView.as_view()
3 - Link to password Rest form in email       //PasswordResetConfirmView.as_view()
4 - Password successfully changed message     //PasswordResetCompleteView.as_view()
'''

base/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Task(models.Model):
    RATING_RANGE = (
        (0, '0'),
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5')
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    article = models.CharField(max_length=100)
    author = models.CharField(max_length=100, blank=True)
    genre = models.CharField(max_length=100, blank=True)
    startDate = models.DateField(auto_now_add=False, auto_now=False, blank=True,null=True)
    endDate = models.DateField(auto_now_add=False,auto_now=False, blank=True,null=True)
    summary = models.TextField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    rating = models.IntegerField(choices=RATING_RANGE)
    # thoughts = models.TextField(null=True, blank=True)
    complete = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True, blank=True)

    def __str__(self):
        return self.article

    class Meta:
        order_with_respect_to = 'user'

class Thought(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    thought = models.CharField(max_length=100,blank=True)

    def __str__(self):
        return self.thought

    class Meta:
        order_with_respect_to = 'user'

base/forms.py
from django import forms
from .models import Task,Thought
from functools import partial
DateInput = partial(forms.DateInput, {'class': 'datepicker'})
# Reordering Form and View

from ReadingJournalApp import settings
class PositionForm(forms.Form):
    position = forms.CharField()
    startDate = forms.DateField(widget=DateInput(), input_formats= settings.DATE_INPUT_FORMATS)
    endDate = forms.DateField(widget=DateInput(), input_formats= settings.DATE_INPUT_FORMATS)
    rating = forms.ChoiceField(choices=Task.RATING_RANGE)

class ThoughtForm(forms.Form):
    highlights = forms.CharField(max_length=100)

base/views.py
from django.http import HttpResponse, Http404, request, HttpResponseRedirect, JsonResponse
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.urls import reverse_lazy

from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login

# Imports for Reordering Feature
from django.views import View
from django.shortcuts import redirect, render, get_object_or_404
from django.db import transaction

from .models import Task,Thought
from .forms import PositionForm,ThoughtForm


class CustomLoginView(LoginView):
    template_name = 'base/login.html'
    fields = '__all__'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('tasks')


class RegisterPage(FormView):
    template_name = 'base/register.html'
    form_class = UserCreationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('tasks')

    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request, user)
        return super(RegisterPage, self).form_valid(form)

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('tasks')
        return super(RegisterPage, self).get(*args, **kwargs)


class TaskList(LoginRequiredMixin, ListView):
    model = Task
    context_object_name = 'tasks'
    success_url = reverse_lazy('tasks')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tasks'] = context['tasks'].filter(user=self.request.user)
        context['count'] = context['tasks'].filter(complete=False).count()

        search_input = self.request.GET.get('search-area') or ''
        if search_input:
            context['tasks'] = context['tasks'].filter(startDate=search_input)

        context['search_input'] = search_input

        return context

    def form_valid(self, form):

        Thought = form.save()
        # if Thought is not None:
        #     login(self.request, Thought)
        return redirect(reverse_lazy('tasks'))


class TaskDetail(LoginRequiredMixin, DetailView):
    model = Task
    context_object_name = 'task'
    template_name = 'base/task.html'


class TaskCreate(LoginRequiredMixin, CreateView):
    model = Task
    fields = ['article','author','genre','startDate','endDate','summary','description','rating','complete']
    success_url = reverse_lazy('tasks')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(TaskCreate, self).form_valid(form)


class TaskUpdate(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ['article','author','genre','startDate','endDate','summary','description','rating','complete']
    success_url = reverse_lazy('tasks')

    # def get(self, request, pk):
    #     try:
    #         data = Task.objects.get(id=pk)
    #         thoughts = self.objects.filter(task=data)
    #     except Task.DoesNotExist:
    #         raise Http404('Data does not exist')
    #
    #     if request.method == 'POST':
    #         form = ThoughtForm(request.POST)
    #         if form.is_valid():
    #             Thought = self(highlights=form.cleaned_data['highlights'],task=data)
    #             Thought.save()
    #             return redirect(f'/task/{pk}')
    #     else:
    #         form = ThoughtForm()
    #
    #     context = {
    #         'data': data,
    #         'form': form,
    #         'thoughts': thoughts,
    #     }
    #     return render(request, 'base/TaskDetail.html', context)

class DeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    context_object_name = 'task'
    success_url = reverse_lazy('tasks')
    def get_queryset(self):
        owner = self.request.user
        return self.model.objects.filter(user=owner)

class TaskReorder(View):
    def post(self, request):
        form = PositionForm(request.POST)

        if form.is_valid():
            positionList = form.cleaned_data["position"].split(',')

            with transaction.atomic():
                self.request.user.set_task_order(positionList)

        return redirect(reverse_lazy('tasks'))


# Save Comment
# def save_thought(request):
#     if request.method=='POST':
#         thought=request.POST['thought']
#         taskpk=request.POST['taskpk']
#         task=Task.objects.get(pk=taskpk)
#         user=request.user
#         Thought.objects.create(
#             task=task,
#             thought=thought,
#             user=user
#         )
#         return JsonResponse({'bool':True})

base/templates/base/login.html
{% extends 'base/main.html' %}
{% block content %}

<div class="header-bar">
    <h1>Login</h1>
</div>

<div class="card-body">
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input class="button" type="submit" value="Login">
    </form>
    <p>Don't have an account? <a href="{% url 'register' %}">Register</a></p>
    <p>Forgot password? <a href="{% url 'reset_password' %}" class="ml-2">Reset password</a></p>
   </div>

{% endblock content %}

base/templates/base/main.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Journal App</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200&display=swap" rel="stylesheet">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/jquery-1.12.4.js"></script>
    <script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</head>

</head>

<body>
<div class="container">
		<div class="row justify-content-center">
			<div class="col-8">
                <h1 class="mt-2">Reading Journal</h1>
				<hr class="mt-0 mb-4">
                {% block content %}
                {% endblock content %}
            </div>
		</div>
</div>

</body>


</html>

base/templates/base/password_reset.html
{% extends 'base/main.html' %}
{% block content %}
<div class="header-bar">
    <h1>Password reset</h1>
</div>
<div class="card-body">
<p>Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.</p>

<form method="post">
	{% csrf_token %}
	{{form}}

	<input type="Submit" name="Send email">
	
</form>
</div>
{% endblock content %}

base/templates/base/password_reset_done.html
{% extends 'base/main.html' %}
{% block content %}
<div class="header-bar">
    <h1>Password reset complete</h1>
</div>
<div class="card-body">
<p>Your password has been set. You may go ahead and log in now.</p>


<a href="{% url 'login' %}">Log in</a></p>
</div>
{% endblock content %}

base/templates/base/password_reset_form.html
{% extends 'base/main.html' %}
{% block content %}

<div class="header-bar">
    <h1>Enter new password</h1>
</div>

<div class="card-body">
<p>Please enter your new password twice so we can verify you typed it in correctly.</p>

<form method="post">

	{% csrf_token %}
	{{form}}
	<input type="Submit" name="Update Password">
	
</form>
</div>
{% endblock content %}

base/templates/base/password_reset_sent.html
{% extends 'base/main.html' %}
{% block content %}
<div class="header-bar">
    <h1>Password reset sent</h1>
</div>

<div class="card-body">
<h3></h3>


<p>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>

<p>If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</p>
</div>
{% endblock content %}

base/templates/base/register.html
{% extends 'base/main.html' %}
{% block content %}

<div class="header-bar">
    <h1>Register</h1>
</div>

<div class="card-body">
    <form method="POST">
        {% csrf_token %}
        <label>{{form.username.label}}</label>
        {{form.username}}

        <label>{{form.password1.label}}</label>
        {{form.password1}}

        <label>{{form.password2.label}}</label>
        {{form.password2}}
        <input style="margin-top:10px ;" class="button" type="submit" value="Register">
    </form>
    <p>Already have an account? <a href="{% url 'login' %}">Login</a></p>
</div>




{% endblock content %}

base/templates/base/task.html
<h1>Task: {{task}}</h1>

base/templates/base/task_confirm_delete.html
{% extends 'base/main.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="header-bar">
    <a href="{% url 'tasks' %}">&#8592; Go Back</a>
</div>

<div class="form-group">
    <form method="POST">
        {% csrf_token %}
        <p>Are your sure you want to delete this Journal? <b>"{{task}}"</b> </p>
        <button class="btn btn-success" type="submit" value="Delete">Delete</button>
    </form>
</div>



{% endblock content %}

base/templates/base/task_form.html
{% extends 'base/main.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="header-bar">
    <a href="{% url 'tasks' %}">&#8592; Back</a>
</div>

    <div class="form-group">
        <form method="POST" novalidate>
            {% csrf_token %}
            {{form|crispy}}
            <button class="btn btn-success" type="submit" value="Submit">Submit</button>
        </form>
    </div>

 <script>
    $(document).ready(function() {
        $('#id_startDate').datepicker();
        $('#id_endDate').datepicker();
    });
 </script>

{% endblock content %}

base/templates/base/task_list.html
{% extends 'base/main.html' %}
{% load crispy_forms_tags %}
{% block content %}
<script src="https://cdn.jsdelivr.net/npm/sortablejs@latest/Sortable.min.js"></script>

<div class="container mt-5">
  <div class="row">
    <div class="col-sm-8">

        <div class="header-bar">
    <div>
        <h3>Hello {{request.user|title}}</h3>
        <h5 style="margin:0">You have <i>{{count}}</i> incomplete Journal{{ count|pluralize:"s" }}</h5>
    </div>
<div class="float-sm-right">
    {% if request.user.is_authenticated %}
    <a href="{% url 'logout' %}">Logout</a> {% else %}
    <a href="{% url 'login' %}">Login</a> {% endif %}
</div>
</div>

        <!-- Hidden form. Form submits new item positions -->
        <form style="display: none;" id="reorderForm" method="post" action="{% url 'task-reorder' %}">
            {% csrf_token %}
            <input type="hidden" id="positionInput" name="position">
        </form>
        <div id="tasklist" class="task-items-wrapper">
    {% for task in tasks %}
    <div class="list-group task-wrapper" data-position="{{task.pk}}">
        <div class="list-group-item">
            {% if task.complete %}
            <div class="task-complete-icon"></div>
            <i><s><a href="{% url 'task-update' task.id %}">{{task}}</a></s></i> {% else %}
            <div class="task-incomplete-icon"></div>
            <a href="{% url 'task-update' task.id %}">{{task}}</a> {% endif %}
             <a class="float-sm-right" href="{% url 'task-delete' task.id %}">&#215;</a>
        </div>
    </div>
    {% empty %}
    <div style="text-align: center; padding-bottom: 10px; line-height: 1em;">
        <h6>No new journal is created.</h6>
        <h6>Create a <a style="text-decoration: none; color: #e53935;" href="{% url 'task-create' %}">New Journal</a> ! </h6>
    </div>
    {% endfor %}
</div>

    </div>
    <div class="col-sm-4">
       <div id="datepicker" class="container"></div>
         {% if tasks|length > 0 %}
    <a id="add-link" href="{% url 'task-create' %}">&#x2b; Add Journal</a>
    {% endif %}
<div id="search-add-wrapper">
    <form method="GET" style="display: flex;" id="postform">
        <input type='text' name='search-area' placeholder="Search Journal" value="{{search_input}}" class="form-control" onchange="postsearch" id = 'search-area'>
        <button class="btn btn-success" type="submit" value='Search'>Search</button>
    </form>

</div>
  </div>
  </div>
</div>

<script>
    var taskList = document.getElementById("tasklist");
    var reorderForm = document.getElementById("reorderForm");
    var positionInput = document.getElementById("positionInput");

    let sortable = Sortable.create(taskList, {
        handle: '.handle',
        ghostClass: 'dropArea',
        chosenClass: 'selectedTask',

    });

    function reordering() {
        const rows = document.getElementsByClassName("task-wrapper");
        let pos = [];
        for (let row of rows) {
            pos.push(row.dataset.position);
        }
        console.log(pos.join(","))
        positionInput.value = pos.join(',');
        reorderForm.submit();
    }

    document.ondrop = reordering
</script>
<script type="text/javascript">
<!--$("#datepicker").datepicker();-->

$("#datepicker").datepicker({
    dateFormat: 'yy-mm-dd',
    onSelect: function(dateText, inst) {
        var date = $(this).val();
        var time = $('#time').val();
        search_area = date;
        $("#search-area").val(search_area);
    }
});

function postsearch() {
        $.ajax({
            type: "POST",
            url: $('#postform').attr('search-area'),
            data: $('#postform').serialize()
        });
    };

</script>
{% endblock content %}